---
title: "Example 1_2"
author: "Kevin Cummiskey"
date: "August 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
odor = read.table(file = "http://www.isi-stats.com/isi2/data/OdorRatings.txt",
                  header = T)
```

Single Mean Model

\[y_{i,j} = \mu + \epsilon_{i,j}\]

Below, I am going to fit the single mean model

```{r}
odor %>% ggplot(aes(x = condition, y = rating)) + geom_boxplot()
mean(odor$rating)

odor = odor %>% mutate(mean1 = mean(rating))
#get residuals
odor = odor %>% mutate(residual1 = rating - mean1)

odor %>% ggplot(aes(y = rating, x = factor(condition))) + geom_boxplot()

#Standard Error
odor %>% summarise(sd(residual1))

#SST
SST = odor %>% summarise(sum(residual1^2))

model = summary(lm(rating ~ 1, data = odor))

```


Separate Means Model

\[y_{i,j} = \mu_j + \epsilon_{i,j}\]


```{r}
odor = odor %>% group_by(condition) %>% mutate(mean2 = mean(rating))
odor = odor %>% group_by()

odor = odor %>% mutate(residual2 = rating - mean2)

#SSE
SSE = odor %>% group_by() %>% summarise(sum(residual2^2))

#SSModel
SSModel = odor %>% summarise(sum((mean2 - mean1)^2))

SSE + SSModel
SST

model = lm(rating ~ condition, data = odor)
summary(model)
anova(model)

```




