---
title: "Example 1_2"
author: "Kevin Cummiskey"
date: "August 29, 2019"
output: rmarkdown::github_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
odor = read.table(file = "OdorRatings.txt",
                  header = T)
```

Let's look at the data:

```{r}
odor %>% ggplot(aes(x = condition, y = rating)) +
  geom_boxplot()
```

Single Mean Model

\[y_{i,j} = \mu + \epsilon_{i,j}\]

```{r}
odor = odor %>% mutate(mean1 = mean(rating))


odor = odor %>% mutate(residuals1 = rating - mean1)

#The standard error of this model is the 
#standard deviation of the residuals

#standard error 
SE = odor %>% summarise(sum(residuals1^2)/47)

#Sum of Squares Total (SST)
SST = odor %>% summarise(sum(residuals1^2))

#Shortcut
model1 = lm(rating ~ 1, data = odor)
summary(model1)

```

Separate Means Model

\[y_{i,j} = \mu_j + \epsilon_{i,j}\]

```{r}
#calculate means for each group
odor = odor %>% group_by(condition) %>% 
  mutate(mean2 = mean(rating))
odor = odor %>% group_by()

#residuals
odor = odor %>% mutate(residuals2 = rating - mean2)

#standard error
SE2 = odor %>% summarise(sqrt(sum((rating - mean2)^2)/46))

#Sums of Squared Error (SSE)
SSE2 = odor %>% summarise(sum((rating - mean2)^2))

SSModel = SST - SSE2

#Shortcut
model2 = lm(rating ~ condition, data = odor)
summary(model2)
anova(model2)

```

Let's test for an association between scent exposure and rating

$H_0: \mu_{\text{Scent}} - \mu_{\text{NoScent}} = 0$

$H_a: \mu_{\text{Scent}} - \mu_{\text{NoScent}} \neq 0$

Randomization Test

```{r}
sim.diff = c()
r.squared = c()
m = 10000 #number of simulations
for(i in 1:m){
  sim.dat = odor %>% mutate(sim.condition = 
                              sample(condition))
  sim.scent = sim.dat %>% filter(sim.condition == "scent")
  sim.noscent = sim.dat %>% filter(sim.condition == "noscent")
  sim.diff[i] = mean(sim.scent$rating) - mean(sim.noscent$rating)
  
  #inference on R^2
  model = lm(rating ~ sim.condition, data = sim.dat)
  r.squared[i] = summary(model)$r.squared
}
hist(sim.diff, breaks = 100)

sum(sim.diff > 1.3)/m

```


